<?php

namespace Tests;

use Pest\Plugins\Environment;
use PHPUnit\Framework\TestCase as BaseTestCase;
use Symfony\Component\Filesystem\Filesystem;

abstract class TestCase extends BaseTestCase
{
    public string $cacheDirectory = __DIR__ . '/../.cache';

    public Filesystem $filesystem;

    protected function setUp(): void
    {
        $this->filesystem = new Filesystem();

        $this->clearCacheDirectory();

        parent::setUp();
    }

    protected function tearDown(): void
    {
        $this->clearCacheDirectory();

        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function isLocal(): bool
    {
        return file_exists(__DIR__ . '/../local.flag');
    }

    private function clearCacheDirectory(): void
    {
        if ($this->isLocal() === false) {
            return;
        }

        if ($this->filesystem->exists($this->cacheDirectory)) {
            $this->filesystem->remove($this->cacheDirectory);
        }
    }

    public function skipOnCi(): static
    {
        if ($this->isLocal() === false) {
            $this->markTestSkipped('This test is skipped on CI.');
        }

        return $this;
    }
}
